# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aafc02bb1b1296f0fb8e4a52e81c2488672c97f2b61e8bcff5eb2e3e8f5c4ca710456453bf17ea6e03c1d10858ca8127ded1fd83e9921b575cfb90328ba09e8c

test:
  secret_key_base: 26f2697e6c57f0eaa9d8a7f3c651832db39c88c3506372a9e9d75216ee2b80189cb00a2c0300c8182153e1f99c3f4e3d25f6fb5a5e4ea822af398a291aeda974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
